"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/style.css";
import { AuthProvider } from "@/context/AuthContext";
import { useEffect } from "react";
import { createTheme, ThemeProvider } from "@mui/material";
// import { io } from "socket.io-client";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const socket = io("http://localhost");

const font = createTheme({
  typography: {
    fontFamily: "neodgm",
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={font}>
      <AuthProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </AuthProvider>
    </ThemeProvider>
  );
}
